const ENGLISH_UI = {
  documentTitle: 'Catch Davel — First Playable',
  canvasLabel: 'Catch Davel first-person game',
  campaignButton: 'M · LEVELS', pauseButton: 'PAUSE', pauseLabel: 'Game paused', paused: 'SIMULATION PAUSED',
  pauseHint: 'Gameplay timers, projectiles, and Davels are frozen.', resumeGame: 'RESUME',
  health: 'HEALTH', energy: 'ENERGY', coins: 'COINS', combo: 'COMBO',
  shopLabel: 'Quantum Coin upgrade shop', shopTitle: 'QUANTUM WORKBENCH',
  shopBalanceSuffix: ' coins · purchases apply before the run', shopClose: 'Press U to close',
  campaignLabel: 'Chapter 1 campaign map', chapter: 'CHAPTER 1', chapterTitle: 'THE NEON WORKSHOP',
  close: 'CLOSE', campaignDescription: 'Hunt the dancing Davels, bank coins, and unlock the route to Chief Wobble.',
  settingsTitle: 'GAMEPLAY, ACCESSIBILITY & AUDIO',
  difficulty: 'Difficulty', difficultyStory: 'Story', difficultyStandard: 'Standard', difficultyHard: 'Hard',
  difficultyLabel: '{difficulty} DIFFICULTY', difficultyNextMission: 'Difficulty saved; applies on the next mission start.',
  language: 'Language', sensitivity: 'Mouse sensitivity',
  renderQuality: 'Render quality', qualityAuto: 'Auto', qualityLow: 'Low', qualityMedium: 'Medium', qualityHigh: 'High',
  textScale: 'Text scale', captions: 'Combat captions', photosensitivitySafe: 'Photosensitivity-safe effects',
  cameraMotion: 'Camera motion', recoilMotion: 'Weapon recoil', shakeMotion: 'Camera shake', flashIntensity: 'Flash intensity',
  masterVolume: 'Master volume', musicVolume: 'Music volume', effectsVolume: 'Effects volume',
  weaponsVolume: 'Weapons', robotsVolume: 'Robots', environmentVolume: 'Environment',
  interfaceVolume: 'Interface cues', voiceVolume: 'Voices',
  dynamicRange: 'Dynamic range', dynamicWide: 'Wide', dynamicBalanced: 'Balanced', dynamicNight: 'Night',
  reducedMotion: 'Reduced motion', highContrast: 'High contrast', settingsHint: 'Settings save to this profile.',
  touchControlScale: 'Touch control size', touchControlOpacity: 'Touch control opacity',
  touchVerticalOffset: 'Touch vertical position', touchHandedness: 'Touch handedness',
  touchRightHanded: 'Right-handed', touchLeftHanded: 'Left-handed', touchDeadZone: 'Stick dead zone',
  touchFireMode: 'Touch firing', touchFireHold: 'Hold to fire', touchFireToggle: 'Tap to toggle',
  sprintMode: 'Sprint input', sprintHold: 'Hold to sprint', sprintToggle: 'Tap to toggle sprint',
  controlsTitle: 'KEYBOARD & MOUSE', resetControls: 'RESET CONTROLS', pressControl: 'Press a key or mouse button · Esc cancels',
  controlSaved: '{action} bound to {control}.', controlForward: 'Move forward', controlBack: 'Move back',
  controlLeft: 'Move left', controlRight: 'Move right', controlSprint: 'Sprint', controlDash: 'Dash', controlFire: 'Fire', controlAltFire: 'Charged / alternate',
  controlCampaign: 'Levels', controlShop: 'Upgrades', controlPulse: 'Pulse weapon', controlSword: 'Sword weapon',
  controlBomb: 'Bomb weapon', controlLaser: 'Laser weapon',
  settingsSaved: 'Settings saved.', exportSave: 'EXPORT SAVE', importSave: 'IMPORT SAVE',
  profileHint: 'Profiles use validated JSON with an integrity checksum.',
  campaignFooter: 'Completed levels stay replayable. Locked levels open in order.',
  resultsLabel: 'Mission results', missionComplete: 'MISSION COMPLETE', completionTime: 'TIME', bestTime: 'BEST',
  parTime: 'PAR', coinsEarned: 'COINS EARNED', replayMission: 'REPLAY', nextMission: 'NEXT MISSION',
  score: 'SCORE', accuracy: 'ACCURACY', damageTaken: 'DAMAGE TAKEN', robotsDefeated: 'DAVELS DEACTIVATED',
  secretsFound: 'SECRETS', highestCombo: 'BEST COMBO', optionalObjectives: 'Optional objectives',
  medalBronze: '● BRONZE', medalSilver: '◆ SILVER', medalGold: '★ GOLD', medalQuantum: '✦ QUANTUM',
  objectivePar: 'Beat Standard par time', objectiveAccuracy: 'Reach 60% ranged accuracy',
  replayProof: 'Replay proof · seed {seed} · checksum {checksum}',
  wobbleScout: 'Wobble Scouts', blueSlider: 'Blue Sliders', yellowSpinner: 'Yellow Spinners',
  redFiremouth: 'Red Firemouths', cyanDj: 'Cyan DJs', invoiceOverlord: 'Invoice Overlords',
  levelMap: 'LEVEL MAP', parMedal: '★ PAR BEAT', clearMedal: 'MISSION CLEAR', newBest: 'NEW BEST', chapterComplete: 'CHAPTER MAP',
  failureLabel: 'Mission failed', missionFailed: 'MISSION FAILED', davelsDeactivated: 'DAVELS DEACTIVATED',
  walletCoins: 'WALLET COINS', retryCheckpoint: 'RETRY CHECKPOINT', restartMission: 'RESTART MISSION',
  retryCheckpointHint: 'The Davels won this round. Resume from your latest stabilized checkpoint.',
  restartMissionHint: 'No checkpoint is stabilized yet. Restart the mission from its entrance.',
  enterDesktop: 'CLICK TO ENTER THE MAZE', enterTouch: 'TOUCH TO ENTER THE MAZE',
  controlsHelp: 'WASD move · Shift sprint · Space dash from Level 11 · mouse aim · hold left fire · right charged attack · 1–4 weapons · U upgrades · M levels · standardized gamepad supported · Esc release',
  touchControls: 'Touch game controls', moveStick: 'Virtual movement stick', dragAim: 'DRAG TO AIM',
  nextWeapon: 'Select next unlocked weapon', alternateAttack: 'Alternate or charged attack', fireWeapon: 'Fire selected weapon',
  alt: 'ALT', fire: 'FIRE', sprint: 'RUN', sprintAction: 'Sprint', dash: 'DASH', dashAction: 'Dash', level: 'LEVEL', locked: 'LOCKED',
  clearedBest: 'CLEARED · BEST {ticks} TICKS', currentMission: 'CURRENT MISSION', ready: 'READY',
  remain: '{count} Davels remain', remainOne: '1 Davel remains', mazeClear: 'maze clear!', reachExit: 'reach the green exit',
  defenseRemain: 'PRIZE BANK {health}/{max} · {count} Davels remain',
  compassKey: 'WORKSHOP KEY', compassDoor: 'WORKSHOP LOCK', compassTicket: 'BRASS TICKET',
  compassTicketGate: 'CARNIVAL GATE', compassCheckpoint: 'CHECKPOINT', compassExit: 'GREEN EXIT',
  compassDistance: '{distance} m away', compassAria: '{target}, {distance} meters away',
  objectiveClearEyebrow: 'MAZE STABILIZED', objectiveClearTitle: 'ROUTE TO {target}',
  objectiveClearDistance: '{distance} m · FOLLOW THE ARROW',
  objectiveClearAria: 'Maze stabilized. Route to {target}, {distance} meters away.',
  waveShift: 'DAVEL SHIFT', waveIncoming: 'WAVE {wave} / {waves} INCOMING',
  waveTime: '{seconds}s', waveAria: 'Davel wave {wave} of {waves} incoming in {seconds} seconds',
  bossHealth: 'THE FINAL INVOICE · {health} HP · phase {phase}',
  bossTitle: 'THE FINAL INVOICE', bossPhaseLabel: 'PHASE {phase}', bossHp: '{health} / {max} HP',
  bossAria: 'The Final Invoice, phase {phase}, {health} of {max} health',
  ringmasterBossTitle: 'RINGMASTER DAVEL',
  ringmasterBossAria: 'Ringmaster Davel, phase {phase}, {health} of {max} health',
  shift: 'DAVEL SHIFT {wave}/{waves} · {seconds}s', overheated: 'OVERHEATED',
  pulse: 'PULSE', sword: 'SWORD', bomb: 'BOMB', laser: 'LASER', bombs: '{count} BOMBS', heat: '{value}% HEAT',
  bombDetonated: 'PULSE BOMB DETONATED', djBeat: 'DJ GRIN DROPPED THE EVIL BEAT',
  bossPhase: 'FINAL INVOICE · PHASE {phase}', keyAcquired: 'WORKSHOP KEY ACQUIRED',
  ringmasterBossPhase: 'RINGMASTER DAVEL · PHASE {phase}',
  ambush: 'WRONG TURN — THE WALLS ARE LAUGHING!', repair: 'REPAIR KIT +{value} HEALTH',
  energyCell: 'PULSE CELL +{value} ENERGY', cache: 'QUANTUM CACHE +{value} COINS',
  doorOpened: 'WORKSHOP LOCK OPEN', checkpoint: 'CHECKPOINT STABILIZED', checkpointBanked: 'CHECKPOINT STABILIZED · +{coins} COINS BANKED', allDavelsDown: 'ALL DAVELS DOWN',
  exitOnline: 'EXIT ONLINE — REACH THE GREEN PORTAL', davelDown: 'DAVEL DOWN +{coins} COINS',
  victory: 'MAZE STABILIZED!', defeat: 'SYSTEM DOWN — DAVELS WIN',
  resynchronized: 'PRESENTATION RESYNCHRONIZED', workerError: 'SIMULATION WORKER ERROR',
  captionsLabel: 'Combat sound captions', directionLeft: 'LEFT', directionCenter: 'AHEAD', directionRight: 'RIGHT',
  danceBeatLabel: 'Dance beat indicator', danceBeatAria: 'Dance beat {beat} of 4 · step {step} of 16 · {phase}',
  danceBeatNeutral: 'dance', danceBeatAttack: 'attack', danceBeatVulnerable: 'vulnerable', danceBeatFrozen: 'freeze',
  captionPulse: '● Pulse shot', captionSword: '● Sword swing', captionChargedSword: '● Charged sword swing',
  captionDeflect: '◆ Projectile deflected', captionBombThrown: '● Pulse bomb thrown', captionLaser: '● Laser beam',
  captionHitConfirmed: '◆ Hit confirmed · {direction}', captionWeakPoint: '✦ WEAK POINT ×1.5 · {direction}',
  captionAttackCharging: '⚠ Davel attack charging · {direction}',
  captionIncoming: '⚠ Incoming projectile · {direction}', captionMelee: '⚠ Davel strike · {direction}',
  captionPlayerHit: '⚠ Damage from {direction}',
  exportPreparing: 'Preparing validated profile export…', exported: 'Profile exported.', exportCancelled: 'Export cancelled.',
  exportRejected: 'Export rejected: {error}', exportFailed: 'Profile export failed.',
  importChoose: 'Choose a Catch Davel JSON profile…', importCancelled: 'Import cancelled.',
  importKept: 'Import cancelled; current progress was kept.', imported: 'Profile imported and verified. Reloading…',
  importRejected: 'Import rejected: {error}', importFailed: 'Profile import failed.',
  replaceProgress: "Replace this device's Catch Davel progress with the selected validated profile?",
  upgradeMax: '{name} · MAX', upgradePrice: '{name} · LV {level} · {cost} COINS',
  upgradeInstalled: '{name} INSTALLED', upgradeFailed: 'UPGRADE FAILED',
  pulseDamageName: 'Pulse Overcharge', pulseEfficiencyName: 'Quantum Capacitor', swordCoolingName: 'Cryo Hilt',
  bombCapacityName: 'Bomb Pockets', laserCoolingName: 'Prism Cooling',
  maxHealthName: 'Reinforced Suit', maxEnergyName: 'Expanded Cell',
  pulseDamageDescription: '+6 pulse damage per level', pulseEfficiencyDescription: '-0.5 pulse energy cost per level',
  swordCoolingDescription: '-12% sword heat per level', bombCapacityDescription: '+1 starting bomb per level',
  laserCoolingDescription: '-12% laser heat per level',
  maxHealthDescription: '+15 maximum health per level', maxEnergyDescription: '+12 maximum energy per level',
} as const;

type RuntimeUiKey = keyof typeof ENGLISH_UI;

const ARABIC_UI: Record<RuntimeUiKey, string> = {
  documentTitle: 'كاتش دافل — النسخة التجريبية الأولى',
  canvasLabel: 'لعبة كاتش دافل بمنظور الشخص الأول',
  campaignButton: 'M · المستويات', pauseButton: 'إيقاف مؤقت', pauseLabel: 'اللعبة متوقفة مؤقتًا', paused: 'المحاكاة متوقفة مؤقتًا',
  pauseHint: 'توقفت مؤقتات اللعب والقذائف وروبوتات دافل.', resumeGame: 'متابعة',
  health: 'الصحة', energy: 'الطاقة', coins: 'العملات', combo: 'السلسلة',
  shopLabel: 'متجر ترقيات عملات كوانتم', shopTitle: 'ورشة كوانتم',
  shopBalanceSuffix: ' عملة · تُطبّق المشتريات قبل الجولة', shopClose: 'اضغط U للإغلاق',
  campaignLabel: 'خريطة حملة الفصل الأول', chapter: 'الفصل الأول', chapterTitle: 'ورشة النيون',
  close: 'إغلاق', campaignDescription: 'طارد روبوتات دافل الراقصة، واجمع العملات، وافتح الطريق إلى الزعيم ووبل.',
  settingsTitle: 'اللعب وإمكانية الوصول والصوت',
  difficulty: 'الصعوبة', difficultyStory: 'القصة', difficultyStandard: 'قياسي', difficultyHard: 'صعب',
  difficultyLabel: 'صعوبة {difficulty}', difficultyNextMission: 'تم حفظ الصعوبة وستُطبق عند بدء المهمة التالية.',
  language: 'اللغة', sensitivity: 'حساسية التصويب',
  renderQuality: 'جودة العرض', qualityAuto: 'تلقائي', qualityLow: 'منخفضة', qualityMedium: 'متوسطة', qualityHigh: 'عالية',
  textScale: 'حجم النص', captions: 'ترجمة القتال', photosensitivitySafe: 'مؤثرات آمنة للحساسية الضوئية',
  cameraMotion: 'حركة الكاميرا', recoilMotion: 'ارتداد السلاح', shakeMotion: 'اهتزاز الكاميرا', flashIntensity: 'شدة الوميض',
  masterVolume: 'الصوت الرئيسي', musicVolume: 'الموسيقى', effectsVolume: 'المؤثرات',
  weaponsVolume: 'الأسلحة', robotsVolume: 'الروبوتات', environmentVolume: 'البيئة',
  interfaceVolume: 'إشارات الواجهة', voiceVolume: 'الأصوات',
  dynamicRange: 'النطاق الديناميكي', dynamicWide: 'واسع', dynamicBalanced: 'متوازن', dynamicNight: 'ليلي',
  reducedMotion: 'تقليل الحركة', highContrast: 'تباين مرتفع', settingsHint: 'تُحفظ الإعدادات في هذا الملف.',
  touchControlScale: 'حجم أزرار اللمس', touchControlOpacity: 'شفافية أزرار اللمس',
  touchVerticalOffset: 'موضع اللمس الرأسي', touchHandedness: 'ترتيب أزرار اللمس',
  touchRightHanded: 'لليد اليمنى', touchLeftHanded: 'لليد اليسرى', touchDeadZone: 'المنطقة الميتة للعصا',
  touchFireMode: 'طريقة إطلاق اللمس', touchFireHold: 'اضغط باستمرار', touchFireToggle: 'المس للتبديل',
  sprintMode: 'طريقة الركض', sprintHold: 'اضغط باستمرار للركض', sprintToggle: 'المس لتبديل الركض',
  controlsTitle: 'لوحة المفاتيح والفأرة', resetControls: 'إعادة ضبط التحكم', pressControl: 'اضغط مفتاحًا أو زر فأرة · Esc للإلغاء',
  controlSaved: 'تم ربط {action} بـ {control}.', controlForward: 'تحرك للأمام', controlBack: 'تحرك للخلف',
  controlLeft: 'تحرك لليسار', controlRight: 'تحرك لليمين', controlSprint: 'ركض', controlDash: 'اندفاع', controlFire: 'إطلاق', controlAltFire: 'هجوم مشحون / بديل',
  controlCampaign: 'المستويات', controlShop: 'الترقيات', controlPulse: 'السلاح النبضي', controlSword: 'سلاح السيف',
  controlBomb: 'سلاح القنبلة', controlLaser: 'سلاح الليزر',
  settingsSaved: 'تم حفظ الإعدادات.', exportSave: 'تصدير الحفظ', importSave: 'استيراد الحفظ',
  profileHint: 'يستخدم ملف الحفظ JSON موثّقًا مع بصمة سلامة.',
  campaignFooter: 'يمكن إعادة المستويات المكتملة، وتُفتح المستويات المقفلة بالترتيب.',
  resultsLabel: 'نتائج المهمة', missionComplete: 'اكتملت المهمة', completionTime: 'الوقت', bestTime: 'الأفضل',
  parTime: 'الوقت القياسي', coinsEarned: 'العملات المكتسبة', replayMission: 'إعادة المهمة', nextMission: 'المهمة التالية',
  score: 'النقاط', accuracy: 'الدقة', damageTaken: 'الضرر المتلقى', robotsDefeated: 'روبوتات دافل المعطلة',
  secretsFound: 'الأسرار', highestCombo: 'أفضل سلسلة', optionalObjectives: 'الأهداف الاختيارية',
  medalBronze: '● برونزية', medalSilver: '◆ فضية', medalGold: '★ ذهبية', medalQuantum: '✦ كوانتم',
  objectivePar: 'تجاوز الوقت القياسي', objectiveAccuracy: 'حقق دقة بعيدة 60٪',
  replayProof: 'إثبات الإعادة · البذرة {seed} · البصمة {checksum}',
  wobbleScout: 'كشافة ووبل', blueSlider: 'منزلقات زرقاء', yellowSpinner: 'دوارات صفراء',
  redFiremouth: 'أفواه النار الحمراء', cyanDj: 'دي جي سماوي', invoiceOverlord: 'زعماء الفاتورة',
  levelMap: 'خريطة المستويات', parMedal: '★ حطمت الوقت القياسي', clearMedal: 'تم إنهاء المهمة', newBest: 'رقم قياسي جديد', chapterComplete: 'خريطة الفصل',
  failureLabel: 'فشلت المهمة', missionFailed: 'فشلت المهمة', davelsDeactivated: 'روبوتات دافل المعطلة',
  walletCoins: 'عملات المحفظة', retryCheckpoint: 'إعادة نقطة الحفظ', restartMission: 'إعادة المهمة',
  retryCheckpointHint: 'فازت روبوتات دافل في هذه الجولة. تابع من آخر نقطة حفظ مستقرة.',
  restartMissionHint: 'لم تثبت نقطة حفظ بعد. أعد المهمة من المدخل.',
  enterDesktop: 'انقر لدخول المتاهة', enterTouch: 'المس لدخول المتاهة',
  controlsHelp: 'WASD للحركة · Shift للركض · Space للاندفاع من المستوى 11 · الفأرة للتصويب · الزر الأيسر للإطلاق · الأيمن للهجوم المشحون · 1–4 للأسلحة · U للترقيات · M للمستويات · يد تحكم قياسية مدعومة · Esc للتحرير',
  touchControls: 'أزرار تحكم اللمس', moveStick: 'عصا الحركة الافتراضية', dragAim: 'اسحب للتصويب',
  nextWeapon: 'اختر السلاح المفتوح التالي', alternateAttack: 'هجوم بديل أو مشحون', fireWeapon: 'أطلق السلاح المحدد',
  alt: 'بديل', fire: 'إطلاق', sprint: 'ركض', sprintAction: 'الركض', dash: 'اندفاع', dashAction: 'الاندفاع', level: 'المستوى', locked: 'مقفل',
  clearedBest: 'مكتمل · الأفضل {ticks} نبضة', currentMission: 'المهمة الحالية', ready: 'جاهز',
  remain: 'متبقٍ {count} من دافل', remainOne: 'متبقٍ دافل واحد', mazeClear: 'تم تطهير المتاهة!', reachExit: 'اتجه إلى المخرج الأخضر',
  defenseRemain: 'بنك الجوائز {health}/{max} · متبقٍ {count} من دافل',
  compassKey: 'مفتاح الورشة', compassDoor: 'قفل الورشة', compassTicket: 'التذكرة النحاسية',
  compassTicketGate: 'بوابة المهرجان', compassCheckpoint: 'نقطة الحفظ', compassExit: 'المخرج الأخضر',
  compassDistance: 'على بعد {distance} م', compassAria: '{target}، على بعد {distance} متر',
  objectiveClearEyebrow: 'تم تثبيت المتاهة', objectiveClearTitle: 'المسار إلى {target}',
  objectiveClearDistance: '{distance} م · اتبع السهم',
  objectiveClearAria: 'تم تثبيت المتاهة. المسار إلى {target}، على بعد {distance} متر.',
  waveShift: 'تبديل دافل', waveIncoming: 'الموجة {wave} / {waves} قادمة',
  waveTime: '{seconds} ث', waveAria: 'موجة دافل {wave} من {waves} قادمة خلال {seconds} ثانية',
  bossHealth: 'الفاتورة الأخيرة · {health} صحة · المرحلة {phase}',
  bossTitle: 'الفاتورة الأخيرة', bossPhaseLabel: 'المرحلة {phase}', bossHp: '{health} / {max} صحة',
  bossAria: 'الفاتورة الأخيرة، المرحلة {phase}، الصحة {health} من {max}',
  ringmasterBossTitle: 'دافل قائد الحلبة',
  ringmasterBossAria: 'دافل قائد الحلبة، المرحلة {phase}، الصحة {health} من {max}',
  shift: 'موجة دافل {wave}/{waves} · {seconds} ث', overheated: 'حرارة زائدة',
  pulse: 'نبضي', sword: 'سيف', bomb: 'قنبلة', laser: 'ليزر', bombs: '{count} قنابل', heat: 'حرارة {value}٪',
  bombDetonated: 'انفجرت القنبلة النبضية', djBeat: 'دي جي غرين أطلق الإيقاع الشرير',
  bossPhase: 'الفاتورة الأخيرة · المرحلة {phase}', keyAcquired: 'حصلت على مفتاح الورشة',
  ringmasterBossPhase: 'دافل قائد الحلبة · المرحلة {phase}',
  ambush: 'منعطف خاطئ — الجدران تضحك!', repair: 'عدة إصلاح +{value} صحة',
  energyCell: 'خلية نبضية +{value} طاقة', cache: 'مخبأ كوانتم +{value} عملة',
  doorOpened: 'تم فتح قفل الورشة', checkpoint: 'تم تثبيت نقطة الحفظ', checkpointBanked: 'تم تثبيت نقطة الحفظ · أودعت {coins} عملة', allDavelsDown: 'تم تعطيل جميع روبوتات دافل',
  exitOnline: 'المخرج جاهز — اتجه إلى البوابة الخضراء', davelDown: 'تم تعطيل دافل +{coins} عملة',
  victory: 'استقرت المتاهة!', defeat: 'تعطل النظام — فاز دافل',
  resynchronized: 'تمت مزامنة العرض', workerError: 'خطأ في محرك المحاكاة',
  captionsLabel: 'ترجمة أصوات القتال', directionLeft: 'يسار', directionCenter: 'أمامك', directionRight: 'يمين',
  danceBeatLabel: 'مؤشر إيقاع الرقص', danceBeatAria: 'نبضة الرقص {beat} من 4 · الخطوة {step} من 16 · {phase}',
  danceBeatNeutral: 'رقص', danceBeatAttack: 'هجوم', danceBeatVulnerable: 'نقطة ضعف', danceBeatFrozen: 'تجميد',
  captionPulse: '● طلقة نبضية', captionSword: '● ضربة سيف', captionChargedSword: '● ضربة سيف مشحونة',
  captionDeflect: '◆ تم صد القذيفة', captionBombThrown: '● ألقيت قنبلة نبضية', captionLaser: '● شعاع ليزر',
  captionHitConfirmed: '◆ إصابة مؤكدة · {direction}', captionWeakPoint: '✦ نقطة ضعف ×1.5 · {direction}',
  captionAttackCharging: '⚠ هجوم دافل يشحن · {direction}',
  captionIncoming: '⚠ قذيفة قادمة · {direction}', captionMelee: '⚠ ضربة دافل · {direction}',
  captionPlayerHit: '⚠ ضرر من {direction}',
  exportPreparing: 'جارٍ تجهيز ملف الحفظ الموثّق…', exported: 'تم تصدير الحفظ.', exportCancelled: 'أُلغي التصدير.',
  exportRejected: 'رُفض التصدير: {error}', exportFailed: 'فشل تصدير الحفظ.',
  importChoose: 'اختر ملف كاتش دافل بصيغة JSON…', importCancelled: 'أُلغي الاستيراد.',
  importKept: 'أُلغي الاستيراد وبقي التقدم الحالي.', imported: 'تم استيراد الملف والتحقق منه. جارٍ إعادة التحميل…',
  importRejected: 'رُفض الاستيراد: {error}', importFailed: 'فشل استيراد الحفظ.',
  replaceProgress: 'هل تريد استبدال تقدم كاتش دافل على هذا الجهاز بملف الحفظ الموثّق؟',
  upgradeMax: '{name} · الحد الأقصى', upgradePrice: '{name} · المستوى {level} · {cost} عملة',
  upgradeInstalled: 'تم تثبيت {name}', upgradeFailed: 'فشلت الترقية',
  pulseDamageName: 'شحن النبضة', pulseEfficiencyName: 'مكثف كوانتم', swordCoolingName: 'مقبض التبريد',
  bombCapacityName: 'جيوب القنابل', laserCoolingName: 'تبريد المنشور',
  maxHealthName: 'البدلة المعززة', maxEnergyName: 'خلية موسعة',
  pulseDamageDescription: '+6 ضرر نبضي لكل مستوى', pulseEfficiencyDescription: '-0.5 من استهلاك طاقة النبضة لكل مستوى',
  swordCoolingDescription: '-12٪ من حرارة السيف لكل مستوى', bombCapacityDescription: '+1 قنبلة بداية لكل مستوى',
  laserCoolingDescription: '-12٪ من حرارة الليزر لكل مستوى',
  maxHealthDescription: '+15 صحة قصوى لكل مستوى', maxEnergyDescription: '+12 طاقة قصوى لكل مستوى',
};

const CATALOGS: Readonly<Record<'en' | 'ar', Readonly<Record<RuntimeUiKey, string>>>> = {
  en: ENGLISH_UI,
  ar: ARABIC_UI,
};

export function runtimeUiText(
  locale: string,
  key: RuntimeUiKey,
  parameters: Readonly<Record<string, string | number>> = {},
): string {
  const template = CATALOGS[locale === 'ar' ? 'ar' : 'en'][key];
  return template.replace(/\{([a-z]+)\}/gi, (match, name: string) => String(parameters[name] ?? match));
}

export type { RuntimeUiKey };
