const ENGLISH_UI = {
  documentTitle: 'Catch Davel — First Playable',
  canvasLabel: 'Catch Davel first-person game',
  campaignButton: 'M · LEVELS',
  health: 'HEALTH', energy: 'ENERGY', coins: 'COINS',
  shopLabel: 'Quantum Coin upgrade shop', shopTitle: 'QUANTUM WORKBENCH',
  shopBalanceSuffix: ' coins · purchases apply before the run', shopClose: 'Press U to close',
  campaignLabel: 'Chapter 1 campaign map', chapter: 'CHAPTER 1', chapterTitle: 'THE NEON WORKSHOP',
  close: 'CLOSE', campaignDescription: 'Hunt the dancing Davels, bank coins, and unlock the route to Chief Wobble.',
  settingsTitle: 'ACCESSIBILITY & AUDIO', language: 'Language', sensitivity: 'Mouse sensitivity',
  masterVolume: 'Master volume', musicVolume: 'Music volume', effectsVolume: 'Effects volume',
  reducedMotion: 'Reduced motion', highContrast: 'High contrast', settingsHint: 'Settings save to this profile.',
  controlsTitle: 'KEYBOARD & MOUSE', resetControls: 'RESET CONTROLS', pressControl: 'Press a key or mouse button · Esc cancels',
  controlSaved: '{action} bound to {control}.', controlForward: 'Move forward', controlBack: 'Move back',
  controlLeft: 'Move left', controlRight: 'Move right', controlFire: 'Fire', controlAltFire: 'Charged / alternate',
  controlCampaign: 'Levels', controlShop: 'Upgrades', controlPulse: 'Pulse weapon', controlSword: 'Sword weapon',
  controlBomb: 'Bomb weapon', controlLaser: 'Laser weapon',
  settingsSaved: 'Settings saved.', exportSave: 'EXPORT SAVE', importSave: 'IMPORT SAVE',
  profileHint: 'Profiles use validated JSON with an integrity checksum.',
  campaignFooter: 'Completed levels stay replayable. Locked levels open in order.',
  enterDesktop: 'CLICK TO ENTER THE MAZE', enterTouch: 'TOUCH TO ENTER THE MAZE',
  controlsHelp: 'WASD move · mouse aim · hold left fire · right charged attack · 1–4 weapons · U upgrades · M levels · standardized gamepad supported · Esc release',
  touchControls: 'Touch game controls', moveStick: 'Virtual movement stick', dragAim: 'DRAG TO AIM',
  nextWeapon: 'Select next unlocked weapon', alternateAttack: 'Alternate or charged attack', fireWeapon: 'Fire selected weapon',
  alt: 'ALT', fire: 'FIRE', level: 'LEVEL', locked: 'LOCKED',
  clearedBest: 'CLEARED · BEST {ticks} TICKS', currentMission: 'CURRENT MISSION', ready: 'READY',
  remain: '{count} Davels remain', mazeClear: 'maze clear!', reachExit: 'reach the green exit',
  bossHealth: 'THE FINAL INVOICE · {health} HP · phase {phase}',
  shift: 'DAVEL SHIFT {wave}/{waves} IN {ticks}', overheated: 'OVERHEATED',
  pulse: 'PULSE', sword: 'SWORD', bomb: 'BOMB', laser: 'LASER', bombs: '{count} BOMBS', heat: '{value}% HEAT',
  bombDetonated: 'PULSE BOMB DETONATED', djBeat: 'DJ GRIN DROPPED THE EVIL BEAT',
  bossPhase: 'FINAL INVOICE · PHASE {phase}', keyAcquired: 'WORKSHOP KEY ACQUIRED',
  ambush: 'WRONG TURN — THE WALLS ARE LAUGHING!', repair: 'REPAIR KIT +{value} HEALTH',
  energyCell: 'PULSE CELL +{value} ENERGY', cache: 'QUANTUM CACHE +{value} COINS',
  doorOpened: 'WORKSHOP LOCK OPEN', checkpoint: 'CHECKPOINT STABILIZED', allDavelsDown: 'ALL DAVELS DOWN',
  exitOnline: 'EXIT ONLINE — REACH THE GREEN PORTAL', davelDown: 'DAVEL DOWN +{coins} COINS',
  victory: 'MAZE STABILIZED!', defeat: 'SYSTEM DOWN — DAVELS WIN',
  resynchronized: 'PRESENTATION RESYNCHRONIZED', workerError: 'SIMULATION WORKER ERROR',
  exportPreparing: 'Preparing validated profile export…', exported: 'Profile exported.', exportCancelled: 'Export cancelled.',
  exportRejected: 'Export rejected: {error}', exportFailed: 'Profile export failed.',
  importChoose: 'Choose a Catch Davel JSON profile…', importCancelled: 'Import cancelled.',
  importKept: 'Import cancelled; current progress was kept.', imported: 'Profile imported and verified. Reloading…',
  importRejected: 'Import rejected: {error}', importFailed: 'Profile import failed.',
  replaceProgress: "Replace this device's Catch Davel progress with the selected validated profile?",
  upgradeMax: '{name} · MAX', upgradePrice: '{name} · LV {level} · {cost} COINS',
  upgradeInstalled: '{name} INSTALLED', upgradeFailed: 'UPGRADE FAILED',
  pulseDamageName: 'Pulse Overcharge', pulseEfficiencyName: 'Quantum Capacitor', swordCoolingName: 'Cryo Hilt',
  bombCapacityName: 'Bomb Pockets', laserCoolingName: 'Prism Cooling',
  pulseDamageDescription: '+6 pulse damage per level', pulseEfficiencyDescription: '-0.5 pulse energy cost per level',
  swordCoolingDescription: '-12% sword heat per level', bombCapacityDescription: '+1 starting bomb per level',
  laserCoolingDescription: '-12% laser heat per level',
} as const;

type RuntimeUiKey = keyof typeof ENGLISH_UI;

const ARABIC_UI: Record<RuntimeUiKey, string> = {
  documentTitle: 'كاتش دافل — النسخة التجريبية الأولى',
  canvasLabel: 'لعبة كاتش دافل بمنظور الشخص الأول',
  campaignButton: 'M · المستويات',
  health: 'الصحة', energy: 'الطاقة', coins: 'العملات',
  shopLabel: 'متجر ترقيات عملات كوانتم', shopTitle: 'ورشة كوانتم',
  shopBalanceSuffix: ' عملة · تُطبّق المشتريات قبل الجولة', shopClose: 'اضغط U للإغلاق',
  campaignLabel: 'خريطة حملة الفصل الأول', chapter: 'الفصل الأول', chapterTitle: 'ورشة النيون',
  close: 'إغلاق', campaignDescription: 'طارد روبوتات دافل الراقصة، واجمع العملات، وافتح الطريق إلى الزعيم ووبل.',
  settingsTitle: 'إمكانية الوصول والصوت', language: 'اللغة', sensitivity: 'حساسية التصويب',
  masterVolume: 'الصوت الرئيسي', musicVolume: 'الموسيقى', effectsVolume: 'المؤثرات',
  reducedMotion: 'تقليل الحركة', highContrast: 'تباين مرتفع', settingsHint: 'تُحفظ الإعدادات في هذا الملف.',
  controlsTitle: 'لوحة المفاتيح والفأرة', resetControls: 'إعادة ضبط التحكم', pressControl: 'اضغط مفتاحًا أو زر فأرة · Esc للإلغاء',
  controlSaved: 'تم ربط {action} بـ {control}.', controlForward: 'تحرك للأمام', controlBack: 'تحرك للخلف',
  controlLeft: 'تحرك لليسار', controlRight: 'تحرك لليمين', controlFire: 'إطلاق', controlAltFire: 'هجوم مشحون / بديل',
  controlCampaign: 'المستويات', controlShop: 'الترقيات', controlPulse: 'السلاح النبضي', controlSword: 'سلاح السيف',
  controlBomb: 'سلاح القنبلة', controlLaser: 'سلاح الليزر',
  settingsSaved: 'تم حفظ الإعدادات.', exportSave: 'تصدير الحفظ', importSave: 'استيراد الحفظ',
  profileHint: 'يستخدم ملف الحفظ JSON موثّقًا مع بصمة سلامة.',
  campaignFooter: 'يمكن إعادة المستويات المكتملة، وتُفتح المستويات المقفلة بالترتيب.',
  enterDesktop: 'انقر لدخول المتاهة', enterTouch: 'المس لدخول المتاهة',
  controlsHelp: 'WASD للحركة · الفأرة للتصويب · الزر الأيسر للإطلاق · الأيمن للهجوم المشحون · 1–4 للأسلحة · U للترقيات · M للمستويات · يد تحكم قياسية مدعومة · Esc للتحرير',
  touchControls: 'أزرار تحكم اللمس', moveStick: 'عصا الحركة الافتراضية', dragAim: 'اسحب للتصويب',
  nextWeapon: 'اختر السلاح المفتوح التالي', alternateAttack: 'هجوم بديل أو مشحون', fireWeapon: 'أطلق السلاح المحدد',
  alt: 'بديل', fire: 'إطلاق', level: 'المستوى', locked: 'مقفل',
  clearedBest: 'مكتمل · الأفضل {ticks} نبضة', currentMission: 'المهمة الحالية', ready: 'جاهز',
  remain: 'متبقٍ {count} من دافل', mazeClear: 'تم تطهير المتاهة!', reachExit: 'اتجه إلى المخرج الأخضر',
  bossHealth: 'الفاتورة الأخيرة · {health} صحة · المرحلة {phase}',
  shift: 'موجة دافل {wave}/{waves} خلال {ticks}', overheated: 'حرارة زائدة',
  pulse: 'نبضي', sword: 'سيف', bomb: 'قنبلة', laser: 'ليزر', bombs: '{count} قنابل', heat: 'حرارة {value}٪',
  bombDetonated: 'انفجرت القنبلة النبضية', djBeat: 'دي جي غرين أطلق الإيقاع الشرير',
  bossPhase: 'الفاتورة الأخيرة · المرحلة {phase}', keyAcquired: 'حصلت على مفتاح الورشة',
  ambush: 'منعطف خاطئ — الجدران تضحك!', repair: 'عدة إصلاح +{value} صحة',
  energyCell: 'خلية نبضية +{value} طاقة', cache: 'مخبأ كوانتم +{value} عملة',
  doorOpened: 'تم فتح قفل الورشة', checkpoint: 'تم تثبيت نقطة الحفظ', allDavelsDown: 'تم تعطيل جميع روبوتات دافل',
  exitOnline: 'المخرج جاهز — اتجه إلى البوابة الخضراء', davelDown: 'تم تعطيل دافل +{coins} عملة',
  victory: 'استقرت المتاهة!', defeat: 'تعطل النظام — فاز دافل',
  resynchronized: 'تمت مزامنة العرض', workerError: 'خطأ في محرك المحاكاة',
  exportPreparing: 'جارٍ تجهيز ملف الحفظ الموثّق…', exported: 'تم تصدير الحفظ.', exportCancelled: 'أُلغي التصدير.',
  exportRejected: 'رُفض التصدير: {error}', exportFailed: 'فشل تصدير الحفظ.',
  importChoose: 'اختر ملف كاتش دافل بصيغة JSON…', importCancelled: 'أُلغي الاستيراد.',
  importKept: 'أُلغي الاستيراد وبقي التقدم الحالي.', imported: 'تم استيراد الملف والتحقق منه. جارٍ إعادة التحميل…',
  importRejected: 'رُفض الاستيراد: {error}', importFailed: 'فشل استيراد الحفظ.',
  replaceProgress: 'هل تريد استبدال تقدم كاتش دافل على هذا الجهاز بملف الحفظ الموثّق؟',
  upgradeMax: '{name} · الحد الأقصى', upgradePrice: '{name} · المستوى {level} · {cost} عملة',
  upgradeInstalled: 'تم تثبيت {name}', upgradeFailed: 'فشلت الترقية',
  pulseDamageName: 'شحن النبضة', pulseEfficiencyName: 'مكثف كوانتم', swordCoolingName: 'مقبض التبريد',
  bombCapacityName: 'جيوب القنابل', laserCoolingName: 'تبريد المنشور',
  pulseDamageDescription: '+6 ضرر نبضي لكل مستوى', pulseEfficiencyDescription: '-0.5 من استهلاك طاقة النبضة لكل مستوى',
  swordCoolingDescription: '-12٪ من حرارة السيف لكل مستوى', bombCapacityDescription: '+1 قنبلة بداية لكل مستوى',
  laserCoolingDescription: '-12٪ من حرارة الليزر لكل مستوى',
};

const CATALOGS: Readonly<Record<'en' | 'ar', Readonly<Record<RuntimeUiKey, string>>>> = {
  en: ENGLISH_UI,
  ar: ARABIC_UI,
};

export function runtimeUiText(
  locale: string,
  key: RuntimeUiKey,
  parameters: Readonly<Record<string, string | number>> = {},
): string {
  const template = CATALOGS[locale === 'ar' ? 'ar' : 'en'][key];
  return template.replace(/\{([a-z]+)\}/gi, (match, name: string) => String(parameters[name] ?? match));
}

export type { RuntimeUiKey };
