import { checksumCanonicalContent } from '../content-hash.ts';
import type { LevelDefinition } from '../level-definition.ts';

const ZERO_HASH = '0000000000000000';

const draft: LevelDefinition = {
  schemaVersion: 1,
  id: 'level-012',
  number: 12,
  chapterId: 'chapter-02',
  nameKey: 'levels.012.name',
  briefingKey: 'levels.012.briefing',
  seed: 'campaign-level-012-v1',
  palette: { presetId: 'copper-carnival-12' },
  maze: {
    templateSetId: 'carnival-sliding-sideshow',
    generatorVersion: 1,
    criticalPathRooms: { minimum: 5, maximum: 5 },
    optionalRooms: { minimum: 1, maximum: 1 },
    maxBranchDepth: 1,
    secretCount: 0,
    entranceNodeId: 'sideshow-entry',
    exitNodeId: 'carousel-exit',
    nodes: [
      { id: 'sideshow-entry', role: 'entrance', templateTags: ['carnival', 'striped-entry'], sizeClass: 'small', encounterIds: [], pickupIds: ['repair-kit'], checkpointId: null, storyIds: [], criticalPath: true },
      { id: 'pass-booth', role: 'corridor', templateTags: ['carnival', 'sideshow-pass'], sizeClass: 'medium', encounterIds: [], pickupIds: ['sideshow-pass'], checkpointId: null, storyIds: [], criticalPath: true },
      { id: 'slider-stage', role: 'arena', templateTags: ['carnival', 'blue-slider', 'dash-course', 'moving-floor'], sizeClass: 'large', encounterIds: ['sliding-sideshow-crew'], pickupIds: ['pulse-cell'], checkpointId: null, storyIds: [], criticalPath: true },
      { id: 'mirror-loop', role: 'corridor', templateTags: ['carnival', 'mirror-maze', 'coin-cache'], sizeClass: 'medium', encounterIds: [], pickupIds: ['coin-cache'], checkpointId: null, storyIds: [], criticalPath: false },
      { id: 'sideshow-checkpoint', role: 'checkpoint', templateTags: ['carnival', 'recovery'], sizeClass: 'small', encounterIds: [], pickupIds: [], checkpointId: 'checkpoint-012', storyIds: [], criticalPath: true },
      { id: 'carousel-exit', role: 'exit', templateTags: ['carnival', 'objective-exit'], sizeClass: 'small', encounterIds: [], pickupIds: [], checkpointId: null, storyIds: [], criticalPath: true },
    ],
    edges: [
      { id: 'entry-pass', from: 'sideshow-entry', to: 'pass-booth', bidirectional: true, requiredKeyId: null, doorType: 'open', traversalCost: 1, stateTrigger: null },
      { id: 'pass-stage', from: 'pass-booth', to: 'slider-stage', bidirectional: true, requiredKeyId: 'sideshow-pass', doorType: 'ticket-gate', traversalCost: 1, stateTrigger: 'key-collected' },
      { id: 'stage-checkpoint', from: 'slider-stage', to: 'sideshow-checkpoint', bidirectional: true, requiredKeyId: null, doorType: 'open', traversalCost: 1, stateTrigger: null },
      { id: 'checkpoint-exit', from: 'sideshow-checkpoint', to: 'carousel-exit', bidirectional: true, requiredKeyId: null, doorType: 'open', traversalCost: 1, stateTrigger: 'primary-objective' },
      { id: 'pass-mirrors', from: 'pass-booth', to: 'mirror-loop', bidirectional: true, requiredKeyId: null, doorType: 'open', traversalCost: 2, stateTrigger: null },
      { id: 'mirrors-checkpoint', from: 'mirror-loop', to: 'sideshow-checkpoint', bidirectional: true, requiredKeyId: 'sideshow-pass', doorType: 'ticket-gate', traversalCost: 2, stateTrigger: 'key-collected' },
    ],
    keys: [{ id: 'sideshow-pass', placementNodeId: 'pass-booth' }],
    hazards: [
      { id: 'slide-belt-north', nodeId: 'slider-stage', periodTicks: 160, activeTicks: 100, collisionProfileId: 'sideshow-slide-north-v1' },
      { id: 'slide-belt-south', nodeId: 'slider-stage', periodTicks: 160, activeTicks: 100, collisionProfileId: 'sideshow-slide-south-v1' },
    ],
    generationAttempts: 1,
    validationProfile: 'authored-grid-v1',
  },
  objectives: [{
    id: 'clear-sliding-sideshow',
    type: 'survive',
    required: true,
    titleKey: 'objectives.level_012',
    targetIds: ['slider-spotlight-wave', 'sideshow-finale-wave'],
    targetCount: 9,
    durationTicks: null,
    dependsOn: [],
    completionMode: 'count',
    markerPolicy: 'always',
  }],
  encounters: [{
    id: 'sliding-sideshow-crew',
    roomNodeId: 'slider-stage',
    trigger: 'on-enter',
    triggerRef: null,
    arenaLock: true,
    waves: [{
      id: 'slider-spotlight-wave',
      startCondition: 'encounter-start',
      startDelayTicks: 0,
      spawnGroups: [
        { id: 'spotlight-sliders', archetypeId: 'blue-slider', count: 2, modifierIds: ['sideshow-star'], spawnPointSetId: 'level-012-arena-1', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-1.sliders', rank: 'normal', accessibilityVerificationId: 'silhouette-blue-slider-v1' },
        { id: 'spotlight-wobblers', archetypeId: 'wobble-scout', count: 2, modifierIds: ['sideshow-heckler'], spawnPointSetId: 'level-012-arena-1', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-1.wobblers', rank: 'normal', accessibilityVerificationId: 'silhouette-wobble-scout-v1' },
      ],
      maxConcurrentRobots: 4,
      interGroupDelayTicks: 16,
      danceTransitionId: null,
      completion: 'all-defeated',
      invalidSpawnPolicy: 'fail-level',
    }, {
      id: 'sideshow-finale-wave',
      startCondition: 'previous-wave-complete',
      startDelayTicks: 45,
      spawnGroups: [
        { id: 'finale-spinners', archetypeId: 'yellow-spinner', count: 2, modifierIds: ['mirror-ball'], spawnPointSetId: 'level-012-arena-2', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-2.spinners', rank: 'normal', accessibilityVerificationId: 'silhouette-yellow-spinner-v1' },
        { id: 'finale-firemouth', archetypeId: 'red-firemouth', count: 1, modifierIds: ['hot-shoe'], spawnPointSetId: 'level-012-arena-2', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-2.firemouth', rank: 'normal', accessibilityVerificationId: 'silhouette-red-firemouth-v1' },
        { id: 'finale-foreman', archetypeId: 'red-firemouth', count: 1, modifierIds: ['hot-shoe-foreman'], spawnPointSetId: 'level-012-arena-2', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-2.foreman', rank: 'elite', accessibilityVerificationId: 'silhouette-red-firemouth-v1' },
        { id: 'finale-dj', archetypeId: 'cyan-dj', count: 1, modifierIds: ['sideshow-conductor'], spawnPointSetId: 'level-012-arena-2', dancePresetId: 'sideways-soft-shoe', aiProfileId: 'chapter-02-stage-12', rewardProfileId: 'chapter-02-coins-12', rngStream: 'encounter.level-012.wave-2.dj', rank: 'elite', accessibilityVerificationId: 'silhouette-cyan-dj-v1' },
      ],
      maxConcurrentRobots: 5,
      interGroupDelayTicks: 14,
      danceTransitionId: 'sideshow-finale',
      completion: 'all-defeated',
      invalidSpawnPolicy: 'fail-level',
    }],
    completion: 'all-defeated',
    rewardId: 'chapter-02-clear-012',
    checkpointOnComplete: null,
  }],
  dance: {
    presetId: 'sideways-soft-shoe',
    grammarVersion: 1,
    bpm: 124,
    timeSignature: '4/4',
    barsPerPhrase: 4,
    footPatternId: 'sideways-soft-shoe-feet-v1',
    torsoPatternId: 'sideways-soft-shoe-torso-v1',
    armPatternId: 'sideways-soft-shoe-arms-v1',
    headAccentId: 'sideways-soft-shoe-head-v1',
    pathPatternId: 'sideways-soft-shoe-path-v1',
    attackBeats: [2, 6, 10, 14],
    vulnerableBeats: [0, 4, 8, 12],
    transitionIds: ['sideshow-finale', 'objective-clear'],
    visualIntensity: 0.84,
    reducedMotionPresetId: 'sideways-soft-shoe-reduced-v1',
  },
  difficulty: { presetId: 'standard-chapter-02-012' },
  economy: { presetId: 'economy-chapter-02-012' },
  checkpoints: [{ presetId: 'checkpoint-012' }],
  audio: { presetId: 'audio-copper-carnival-012' },
  mastery: [{ presetId: 'level-012-par-time' }, { presetId: 'level-012-dash-dodger' }],
  agentValidation: {
    tier: 'ordinary',
    owner: 'gameplay-qa',
    runs: [{
      id: 'standard-live',
      mode: 'live-agent',
      policyId: 'baseline-campaign-agent',
      policyVersion: 1,
      referenceReplayId: null,
      seed: 'campaign-level-012-v1',
      difficulty: 'Standard',
      assistProfileId: null,
      maxTicks: 11_000,
      stuckTimeoutTicks: 1_500,
      maxIllegalActions: 0,
      requiredObjectiveIds: ['clear-sliding-sideshow'],
      expectedCompletion: true,
      expectedChecksum: null,
      parTicks: 8_000,
      dependencyHashes: {
        simulationSchema: '6cafd562c735e11d',
        effectiveLevel: ZERO_HASH,
        simulationLevel: '542d63184f1def41',
        balanceData: '1f697b70870c7801',
        policyOrReplay: '33ce82519e6acf00',
      },
    }],
  },
  performance: {
    maxActiveRobots: 5,
    maxActiveProjectiles: 40,
    maxActivePickups: 4,
    maxHazards: 2,
    maxMazeNodes: 8,
    maxRenderInstances: 1_024,
    expectedPeakDrawCalls: 8,
    expectedPeakMemoryMb: 192,
    benchmarkScenarioIds: ['level-012-standard-live'],
  },
  tags: ['chapter-02', 'copper-carnival', 'blue-slider', 'dash-course', 'moving-floor', 'sideways-soft-shoe'],
};

const normalizedForHash: LevelDefinition = {
  ...draft,
  agentValidation: {
    ...draft.agentValidation,
    runs: draft.agentValidation.runs.map((run) => ({
      ...run,
      dependencyHashes: {
        simulationSchema: ZERO_HASH,
        effectiveLevel: ZERO_HASH,
        simulationLevel: ZERO_HASH,
        balanceData: ZERO_HASH,
        policyOrReplay: ZERO_HASH,
      },
    })),
  },
};

const effectiveLevel = checksumCanonicalContent(normalizedForHash);

export const LEVEL_012: LevelDefinition = {
  ...draft,
  agentValidation: {
    ...draft.agentValidation,
    runs: draft.agentValidation.runs.map((run) => ({
      ...run,
      dependencyHashes: { ...run.dependencyHashes, effectiveLevel },
    })),
  },
};
